ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /workspace
ENV TZ=Asia/Shanghai
ENV arch=x86_64
ENV DEBIAN_FRONTEND=noninteractive

# install python
RUN apt-get update && apt-get install --no-install-recommends -y \
  git \
  git-lfs \
  wget \
  curl \
  vim \
  nginx \
  python3-dev \
  python3-venv \
  python3-pip && \
  apt-get clean

# install jupyterlab
RUN pip3 install --no-cache-dir jupyterlab ipywidgets ipykernel matplotlib
COPY --from=proxy nginx.conf /etc/nginx/nginx.conf
COPY --from=scripts start.sh /
COPY --from=scripts podwise_info.sh /etc/podwise-motd 
RUN chmod +x /start.sh && echo "source /etc/podwise-motd" >> ~/.bashrc 

CMD ["/start.sh"

